import type { SecureMessage } from "./types";

const now = Date.now();
const inFuture = (mins: number) => new Date(now + mins * 60_000).toISOString();
const inPast = (mins: number) => new Date(now - mins * 60_000).toISOString();

export const initialMessages: SecureMessage[] = [
  {
    id: "m1",
    folder: "inbox",
    sender: "Aanya Sharma",
    preview: "Wire transfer credentials for the Q4 close…",
    content:
      "Here are the wire transfer credentials for the Q4 close. Please confirm receipt and rotate after use.",
    type: "text",
    protection: "password",
    password: "demo1234",
    expiresAt: inFuture(45),
    viewOnce: true,
    status: "new",
    timestamp: inPast(8),
    views: 0,
    logs: [],
  },
  {
    id: "m2",
    folder: "inbox",
    sender: "Marcus Lee",
    preview: "Voice note · 0:32",
    content: "Voice message — confidential strategy discussion.",
    type: "voice",
    protection: "quick",
    expiresAt: inFuture(120),
    viewOnce: false,
    status: "viewed",
    timestamp: inPast(95),
    views: 2,
    logs: [
      { viewedAt: inPast(80), ip: "192.168.1.4", device: "Chrome · macOS" },
      { viewedAt: inPast(40), ip: "192.168.1.4", device: "Safari · iOS" },
    ],
  },
  {
    id: "m3",
    folder: "inbox",
    sender: "Priya Nair",
    preview: "contract-final.pdf · 1.2 MB",
    content: "Attached: signed NDA. Self-destructs in 1 hour.",
    type: "file",
    protection: "key",
    password: "SK-9F2A-7C81",
    expiresAt: inFuture(60),
    viewOnce: false,
    status: "new",
    timestamp: inPast(180),
    views: 0,
    logs: [],
  },
  {
    id: "m4",
    folder: "inbox",
    sender: "DevOps Bot",
    preview: "Looks like a routine status update…",
    content: "STEALTH PAYLOAD: Production root key rotated at 03:14 UTC.",
    type: "text",
    protection: "quick",
    expiresAt: inFuture(30),
    viewOnce: true,
    status: "new",
    timestamp: inPast(220),
    views: 0,
    logs: [],
    stealth: true,
  },
  {
    id: "m7",
    folder: "inbox",
    sender: "Elena Rossi",
    preview: "Board meeting prep notes",
    content:
      "Quick heads-up before tomorrow's board sync: the revised forecast lands at +12% YoY. Please keep this between us until the official deck drops.",
    type: "text",
    protection: "firstAccess",
    expiresAt: inFuture(180),
    viewOnce: false,
    status: "new",
    timestamp: inPast(15),
    views: 0,
    logs: [],
    accessed: false,
  },
  {
    id: "m5",
    folder: "sent",
    sender: "You → finance@acme.co",
    preview: "Tax IDs and routing numbers",
    content: "Tax IDs and routing numbers for vendor onboarding.",
    type: "text",
    protection: "password",
    password: "vendor2025",
    expiresAt: inFuture(1440),
    viewOnce: false,
    status: "viewed",
    timestamp: inPast(60 * 6),
    views: 1,
    logs: [{ viewedAt: inPast(60 * 5), ip: "10.0.4.21", device: "Edge · Windows" }],
  },
  {
    id: "m6",
    folder: "expired",
    sender: "You → legal@partner.io",
    preview: "Settlement draft v3",
    content: "[Content destroyed]",
    type: "file",
    protection: "password",
    expiresAt: inPast(120),
    viewOnce: true,
    status: "expired",
    timestamp: inPast(60 * 24),
    views: 1,
    logs: [{ viewedAt: inPast(60 * 23), ip: "203.0.113.4", device: "Firefox · Linux" }],
  },
];