/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AnonymousRouteImport } from './routes/anonymous'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MMessageIdRouteImport } from './routes/m.$messageId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonymousRoute = AnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MMessageIdRoute = MMessageIdRouteImport.update({
  id: '/m/$messageId',
  path: '/m/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anonymous': typeof AnonymousRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/m/$messageId': typeof MMessageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anonymous': typeof AnonymousRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/m/$messageId': typeof MMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anonymous': typeof AnonymousRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/m/$messageId': typeof MMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anonymous'
    | '/landing'
    | '/login'
    | '/signup'
    | '/m/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anonymous' | '/landing' | '/login' | '/signup' | '/m/$messageId'
  id:
    | '__root__'
    | '/'
    | '/anonymous'
    | '/landing'
    | '/login'
    | '/signup'
    | '/m/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnonymousRoute: typeof AnonymousRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MMessageIdRoute: typeof MMessageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anonymous': {
      id: '/anonymous'
      path: '/anonymous'
      fullPath: '/anonymous'
      preLoaderRoute: typeof AnonymousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$messageId': {
      id: '/m/$messageId'
      path: '/m/$messageId'
      fullPath: '/m/$messageId'
      preLoaderRoute: typeof MMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnonymousRoute: AnonymousRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MMessageIdRoute: MMessageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
